env:
  es2021: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
globals:
  imports: readonly
